site_name: Samuel's å­¦ä¹ å·¥ä½œç«™
site_url: https://3samuelw.github.io/note/
site_author: Samuel Wang
site_description: "è®°å½•å¹¶åˆ†äº«æˆ‘çš„å­¦ä¹ ä¸é¡¹ç›®ç»å†"

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢åˆ°æ·±è‰²æ¨¡å¼
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢åˆ°æµ…è‰²æ¨¡å¼
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.tabs.link
    - toc.follow
    - mathjax
  icon:
    repo: fontawesome/brands/github

extra_css:
  - extra.css
extra_javascript:
  - extra.js

nav:
  - ğŸ  é¦–é¡µ: index.md
  - ğŸ“ è¯¾ç¨‹ç¬”è®°: 
    - BMEè¯¾ç¨‹ ğŸ“: 
      - å·¥ç¨‹ç”Ÿç†å­¦: 
        - æ‘˜è¦: notes/bme/engineering-physiology/index.md
        - è¯¾ç¨‹ç¬”è®°: notes/bme/engineering-physiology/notes-online.md
      - å¾®æœºåŸç†åŠåº”ç”¨:
        - æ‘˜è¦: notes/bme/micro-computer/index.md
        - å®éªŒæŠ¥å‘Š: notes/bme/micro-computer/reports.md
    - CSè¯¾ç¨‹ ğŸ‘¨â€ğŸ’»:
      - ç¼˜èµ·: notes/cs/signup.md
    - è¯­è¨€å­¦ä¹  ğŸŒ:
      - é˜¿æ‹‰ä¼¯è¯­/Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©:
        - å­¦ä¹ ç¬”è®°: notes/lan/arabic/arabic.md
      - æ³•è¯­/FranÃ§ais:
        - å­¦ä¹ ç¬”è®°: notes/lan/french/french.md
        - æ³•è¯­è¯­æ³•æ•´ç†: notes/lan/french/grammaire.md
      - è·å…°è¯­/Nederlands:
        - å­¦ä¹ ç¬”è®°: notes/lan/dutch/dutch.md
    - Samuelå­¦BCI ğŸ§ :
      - è¯´æ˜: notes/bci/index.md
      - ç¥ç»ç§‘å­¦åŸºç¡€ä¸ç–¾ç—…: notes/bci/neuroscience/notes.md
      - ç¥ç»ç”Ÿç‰©å­¦: notes/bci/neurobiology/notes.md
  - ğŸš€ é¡¹ç›®å±•ç¤º:
    - projects/index.md
    # - é¡¹ç›®A: projects/project-a.md
    # - é¡¹ç›®B: projects/project-b.md
  - ğŸ› ï¸ å·¥å…·èµ„æº:
    - tools/index.md
    - å¼€å‘å·¥å…·: tools/development-tools.md
    - æœ‰ç”¨èµ„æº: tools/useful-resources.md
    - æ•™ç¨‹æ”¶é›†: tools/tutorials.md
  - ğŸ‘¤ å…³äºæˆ‘: about.md

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - glightbox

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.blocks.caption

repo_url: https://github.com/3SamuelW/note
edit_uri: edit/main/docs/